#!/usr/bin/env python
import os
import sys

TOOL="llvm/bin/llvm-as"

fullFileName = os.path.realpath(__file__)
path = os.path.dirname(fullFileName)
fileName = fullFileName[fullFileName.rfind('/'):]
args = sys.argv[1:]
args.insert(0, fileName)
os.execv(path + "/../" + TOOL, args)
