#!/usr/bin/env python
import os
import sys
fullFileName = os.path.realpath(__file__)
path = os.path.realpath(os.path.dirname(fullFileName) + '/../') + '/'

TOOL = "llvm/bin/llvm-ranlib"
POSTARGS = [ ]

fileName = fullFileName[fullFileName.rfind('/'):]
args = sys.argv[1:]
args.insert(0, fileName)
args.extend(POSTARGS)
#print(path + TOOL, args)
os.execv(path + TOOL, args)
