#!/usr/bin/env python
import os
import sys
fullFileName = os.path.realpath(__file__)
path = os.path.realpath(os.path.dirname(fullFileName) + '/../../') + '/'
fileName = fullFileName[fullFileName.rfind('/')+1:]
args = sys.argv[1:]
args.insert(0, fileName)
DEBUG=1 if 'WASM_DEBUG' in os.environ else 0

if ('-L/lib' in args): del args[args.index('-L/lib')]

TOOL = "build/lld/bin/lld"
POSTARGS = [
    '-z', 'relro',
    '-z', 'now',
    #'-L' + path + 'musl/lib/'
]

args.extend(POSTARGS)
if (DEBUG):
    line = [path + TOOL]
    line.extend(args[1:])
    print >> sys.stderr, ' '.join(line)
os.execv(path + TOOL, args)
